# Generated by Django 3.0.5 on 2022-05-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20220521_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
