# Generated by Django 3.0.5 on 2022-05-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_question_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='code',
        ),
        migrations.AddField(
            model_name='result',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
