# Generated by Django 3.0.5 on 2022-06-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20220522_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='Output Result'),
        ),
    ]
